import javax.swing.*;
import java.time.YearMonth;

/**
 *
 * @author rendy
 */
public class HitungHariFrame extends javax.swing.JFrame {
    /**
     * Creates new form HitungHariFrame
     */
    public HitungHariFrame() {
        initComponents();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbBulan = new javax.swing.JComboBox<>();
        spinnerTahun = new javax.swing.JSpinner();
        btnHitung = new javax.swing.JButton();
        labelHasil = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jCalendar2 = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 40, 157));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        jLabel1.setText("Aplikasi Penghitungan Hari");

        cbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        spinnerTahun.setModel(new javax.swing.SpinnerNumberModel(2023, 1900, 2100, 1));
        spinnerTahun.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerTahunStateChanged(evt);
            }
        });

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        labelHasil.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelHasil.setText("hasil...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHasil)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addComponent(jCalendar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(310, 310, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
    try {
            // Mendapatkan bulan dan tahun dari JComboBox dan JSpinner
            int bulan = cbBulan.getSelectedIndex() + 1; // Januari = 1, dst.
            int tahun = (int) spinnerTahun.getValue();

            // Menggunakan LocalDate untuk menghitung jumlah hari dalam bulan dan tahun yang dipilih
            java.time.LocalDate tanggalDariComboBox = java.time.LocalDate.of(tahun, bulan, 1);
            int jumlahHariDariComboBox = tanggalDariComboBox.lengthOfMonth();

            // Mendapatkan hari pertama dan terakhir dalam bulan tersebut
            java.time.LocalDate hariPertama = tanggalDariComboBox.withDayOfMonth(1);
            java.time.LocalDate hariTerakhir = tanggalDariComboBox.withDayOfMonth(jumlahHariDariComboBox);

            // Mengecek apakah tahun kabisat
            boolean isKabisat = java.time.Year.of(tahun).isLeap();

            // Mengambil tanggal dari JCalendar pertama (jCalendar1) untuk selisih hari
            java.util.Date selectedDate1 = jCalendar1.getDate();
            java.util.Date selectedDate2 = jCalendar2.getDate();
            long selisihHari = 0;

            // Menghitung selisih hari jika kedua tanggal dipilih
            if (selectedDate1 != null && selectedDate2 != null) {
                java.time.LocalDate tanggal1 = selectedDate1.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
                java.time.LocalDate tanggal2 = selectedDate2.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
                selisihHari = java.time.temporal.ChronoUnit.DAYS.between(tanggal1, tanggal2);
            }

            // Menampilkan hasil di JLabel
            String hasil = "Jumlah hari: " + jumlahHariDariComboBox +
                           "\n, Hari pertama: " + hariPertama.getDayOfWeek() +
                           "\n, Hari terakhir: " + hariTerakhir.getDayOfWeek() +
                           "\n, Tahun Kabisat: " + (isKabisat ? "Ya" : "Tidak");

            if (selectedDate1 != null && selectedDate2 != null) {
                hasil += "\n, Selisih hari antara kedua tanggal: " + Math.abs(selisihHari) + " hari";
            }

            labelHasil.setText(hasil);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Input tidak valid.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void spinnerTahunStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerTahunStateChanged
      // Mendapatkan tahun yang baru diubah dari JSpinner
        int tahun = (int) spinnerTahun.getValue();

        // Mendapatkan bulan yang dipilih dari JComboBox
        int bulan = cbBulan.getSelectedIndex() + 1; // Januari = 1, dst.

        // Menggunakan LocalDate untuk mendapatkan jumlah hari dalam bulan dan tahun yang baru
        java.time.LocalDate tanggal = java.time.LocalDate.of(tahun, bulan, 1);
        int jumlahHari = tanggal.lengthOfMonth();

        // Menampilkan hasil jumlah hari di JLabel setiap kali tahun diubah
        labelHasil.setText("Jumlah hari: " + jumlahHari);
    }//GEN-LAST:event_spinnerTahunStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HitungHariFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HitungHariFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JComboBox<String> cbBulan;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelHasil;
    private javax.swing.JSpinner spinnerTahun;
    // End of variables declaration//GEN-END:variables
}
